### ISSUE TITLE
Support for multiple locations (europe-west1, etc...)

### ISSUE THREAD

**Issue by crisol3036** [memes/terraform-google-cloudbuild#46]
## Describe the feature

A feature to create cloud build triggers in regions other than `global`. As of now there's no `location` parameter, and by default they all fall under `location = "global"`, as you can see in this resource description when I try to `terraform apply`

```tf
Terraform will perform the following actions:

  # module.cloudbuild_github.module.trigger.google_cloudbuild_trigger.trigger will be created
  + resource "google_cloudbuild_trigger" "trigger" {
      + create_time    = (known after apply)
      + disabled       = false
      + filename       = "cloudbuild.yml"
      + id             = (known after apply)
      + ignored_files  = []
      + included_files = []
      + location       = "global"
      + name           = "my-name"
      + project        = "my-project"
      + tags           = []
      + trigger_id     = (known after apply)

      + approval_config {
          + approval_required = (known after apply)
        }

      + github {
          + name  = "my-repo-name"
          + owner = "my-repo-owner"

          + push {
              + branch       = "master"
              + invert_regex = false
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

Running `terraform apply` fails because it doesn't recognize my Github repository that I've connected to Cloud Build because I've connected it using `europe-west1` as the region. I'd like to continue using the `europe-west1` the region in all my resources

```tf
Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.cloudbuild_github.module.trigger.google_cloudbuild_trigger.trigger: Creating...
╷
│ Error: Error creating Trigger: googleapi: Error 400: Repository mapping does not exist.
Please visit https://console.cloud.google.com/cloud-build/triggers;region=global/connect?project=123
to connect a repository to your project
```

## What I propose

An input parameter `location` at the root of the `cloudbuild_github` module, that would directly affect the `location` parameter [in the `google_cloudbuild_trigger` resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#example-usage---cloudbuild-trigger-filename)

To have something like this:

```tf
module "cloudbuild_github" {
    source  = "memes/cloudbuild/google//modules/github"
    version = "1.0.1"
    ...
    location = "europe-west1"
}
```

**Comment by memes** [comment]
Hello @crisol3036, and thanks for the suggestion - adding a location that defaults to 'global' for backward compatibility makes a lot of sense. I'll reach out today or tomorrow when there is a testing branch and get your feedback.

**Comment by memes** [comment]
@crisol3036, release 1.1.0 is available in Terraform registry which adds `location` variable as an optional input to the modules.

**Comment by crisol3036** [comment]
@memes Thank you! Just tried it and it worked!
